version: '3.1'

services:
  dev_codeigniter4_php:
    build:
      context: ./
      dockerfile: ./Development
    restart: always
    container_name: dev_codeigniter4_php
    volumes:  
      - ./public:/var/www/html/public
      - ./app/Config:/var/www/html/app/Config
      - ./app/Controllers:/var/www/html/app/Controllers
      - ./app/Database:/var/www/html/app/Database
      - ./app/Entities:/var/www/html/app/Entities
      - ./app/Filters:/var/www/html/app/Filters
      - ./app/Helpers:/var/www/html/app/Helpers
      - ./app/Language:/var/www/html/app/Language
      - ./app/Models:/var/www/html/app/Models
      - ./app/ThirdParty:/var/www/html/app/ThirdParty
      - ./app/Views:/var/www/html/app/Views
      - ./app/Common.php:/var/www/html/app/Common.php
      - ./.env:/var/www/html/.env

  dev_codeigniter4_nginx:
    image: nginx:alpine
    restart: always
    container_name: dev_codeigniter4_nginx
    volumes:
      - ./public:/var/www/html/public
      - ./writable:/var/www/html/writable
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/dev/nginx/sites/:/etc/nginx/sites-available
      - ./docker/dev/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8094:80"

  dev_codeigniter4_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: dev_codeigniter4_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - 3001:3306
    volumes: 
      - ./docker/mysql:/docker-entrypoint-initdb.d