version: '3.1'

services:
  codeigniter_php:
    build:
      context: ./
      dockerfile: ./Production
    restart: always
    container_name: codeigniter_php

  codeigniter_nginx:
    image: nginx:alpine
    restart: always
    container_name: codeigniter_nginx
    volumes:
      - ./public:/var/www/html/public
      - ./writable:/var/www/html/writable
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8094:80"

  codeigniter_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: codeigniter_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - 3001:3306
    volumes: 
      - ./docker/mysql:/docker-entrypoint-initdb.d